---
title: "Geospatial Analytics Project"
subtitle: Democratising Geospatial Data and Analytics with Shiny App
date: "31 Dec, 2023"
date-modified: "last-modified"
format: html
toc: true
execute: 
  freeze: true
---

## Overview

The purpose of the geospatial analytics project is to provide students first hand experience on building web-based geospatial analytics tool by integrating open source web mapping API(s), data visualisation API(s) and geospatial analysis libraries. You will also learn how to collecting, processing and analysing spatially related issues using real world data. Students are encouraged to focus on research topics that are relevant to their field of study.

The project is team work. Students are required to form a project team of **2-3** members by the first week of the academic term. Each project teams must start thinking about their project ideas after the first lesson. They are expected to discuss their project topic and scope of works with the instructor before the end of **Week 8**. A project proposal in the form website edited using [Quarto](https://quarto.org/docs/websites/) and publish on [Netlify](https://www.netlify.com/) will be prepared and the link must be provided on eLearn by the end of **Week 8**.

The project proposal should describe the motivation of the project, problems or issues that the project will address, the relevant related work, the approach the team plans to take to solve the problem, and early prototypes or storyboards. The project teams should take advantage of this proposal as a chance to get feedback on the direction of the project from their peers.

Students are required to update their project websites with all the details including the final application, user guide, poster, practice research paper by **the end of week 14**.

## Project Theme

Students are required to choose one of the following theme to develop the GeoSpaital Analytics Project:

-   Spatial Point Patterns Analysis
-   Exploratory Spatial Data Analysis
-   Analytical Regionalisation and Geographical Segmentation
-   Geographically Weighted Regression Models
-   Flow and Movement Data Analytics
-   Geographical Accessibility and Spatial Interaction Models

Please feel free to approach me for more details.

## Potentially Useful Data Source

-   [National Statistical Office](http://statbbi.nso.go.th/staticreport/page/sector/en/01.aspx) Thailand.
-   [Philippine Statistics Authority](https://psa.gov.ph/)
-   [Vietnam Provincial Competitiveness Index](https://pcivietnam.vn/en)
-   [GENERAL STATISTICS OFFICE](https://www.gso.gov.vn/en/homepage/), Vietnam.
-   [Myanmar Information Management Unit](https://themimu.info/)
-   [Armed Conflict Location & Event Data Project (ACLED)](https://acleddata.com/).
-   [Indonesia Geospatial](https://www.indonesia-geospasial.com/)

## Project Milestone

-   Brainstorming project ideas and consulting with course instructor between **Week 2 to Week 7**.
-   Editing and publishing project proposal by the end of **Week 8**.
-   Submission of project poster: **4th April 2024 by 11:59pm (mid-night)**
-   Townhall presentation: **8th April 2024 (Monday)**, at 12:00-2:00pm. Venue: LKSLIB Basement concourse. Students are required to be at the venue latest by 11:30am to setup your project poster.
-   Submission of updated project webpage, final application, user guide, project poster and artifacts: **14th April 2024 by 11:59pm (mid-night)**

## Project Deliverables

### Project Website

#### Project Github

At the beginning of the project, project teams are required to create a project [Github](https://github.com/). The project Github should include all the materials used to develop the project and the written materials such as proposal, poster and practice research paper. It must be used to maintain a complete project versioning including the application and project documents. The Github link must be included in the project proposal. By the end of the project, the project team must pack the final version of the Github repository and upload onto eLearn for final submission. The Github link also must be provided on eLearn.

#### Project Website

Each project team are required to create the project website by using [Quatro](https://quarto.org/docs/websites/). It will be disseminated by using [Netfity](https://www.netlify.com/) web service.

As a first step, you should create a project summary at the course wiki that includes:

-   The title of your project,
-   A short description of not more than 350 word summarising the motivation, objectives, main features of the application your team are going to build, and
-   The project proposal. This should in a webblog page (remember to provide a link at eLearn).

### Poster

The project poster should provide an overview of your project. It should include, but not limited to the following information:

-   Issues and problems - A clear statement of the issues or/and problems your project addresses.

-   Motivation - An explanation of why the issues and/or problems are interesting and what make them difficult to solve.

-   Approach - A description of the techniques or algorithms you used to solve the problem.

-   Results - Screenshots and a working demo of the system you built.

-   Future Work - An explanation of how the work could be extended.

The dimensions for the poster must conform to the International Standards Organization (ISO) poster size format (A1).

-   Size = ISO A1 (594 × 841mm or 23.39 × 33.11inci)
-   Resolution = 300dpi or above
-   File format = jpeg

Please ensure that the poster is in high resolution.

The poster will be considered as a final deliverable. So don't forget to apply good visual design principles to both your poster and project report.

Note: The course instructor will be responsible for printing your poster. You are required to upload your poster onto the project Dropbox of eLearn according to the submission deadline provided on the project milesotne sub-section.

### Peer Evaluation

This component is not a typical peer evaluation of project. For Geospatial Analytics Project, students are required to evaluate at least three applications prepared by your coursemate during the townhall presentation session. A peer evaluation form will be provided. Each team only need to submit one report.

### Final Deliverables

The final deliverable will include:

-   updated project webpage.
-   artifact including the ShinyApp, data and all r modules.
-   User Guide - Step-by-step guide on how to use the Shiny Applications.
-   project poster

## Grading

The geospatial analytics project will account for 30% of your final grade in the course. The distribution of marks for each stage of the project are as follows:

-   Project website 25%
-   Poster 10%
-   Peer Evaluation 15%
-   ShinyApp 50%

The course instructor will consider strongly the novelty of the idea (If it has never been done before, you will get lots of credit!), how it addresses the problem at hand, the methodology you employ in doing the research, and your technical skill in implementing the idea.

In small group projects, each person will be graded individually. A good group project is a system consisting of a collection of well defined subsystems. Each subsystem should be the responsibility of one person and be clearly identified as their project. A good criteria for whether you should work in a group is whether the system as a whole is greater than the sum of its parts!

### Grading criteria for poster

The poster will be graded based on the following criteria:

-   Clear communication of key aspects of solution
-   Clear communication of design approaches
-   Clear communication of arguments for proposed solution
-   Craft quality of the solution

## Reference

-   Paula Moraga (2017) "SpatialEpiApp : A Shiny web application for the analysis of spatial and spatio-temporal disease data", *Spatial and Spatio-temporal Epidemiology*, 23, pp. 47-57. Access using SMU e-journal.

-   Javier De La Hoz-M, Susana Mendes & María José Fernandez-Gómez (2022) ["GeoWeightedModel : An R-Shiny package for Geographically Weighted Models"](https://www.sciencedirect.com/science/article/pii/S2352711022001686), *SoftwareX*, 20.

-   Mario Figueira, David Conesa & Antonio L´opez-Quílez (2024) ["A shiny R app for spatial analysis of species distribution models"](https://www.sciencedirect.com/science/article/pii/S1574954124000840), *Ecological Informatics*, 80.

## Learning from past project

### Must review project

-   [SGSAS: Simple Geo-Spatial Analysis using R-Shiny](https://wiki.smu.edu.sg/1920t2isss608/Group11_proposal) especially gwr sub-module of the [application](https://isss608.shinyapps.io/shiny/).

### Others

-   AY2018-19 Term 2

    -   [Signal](https://wiki.smu.edu.sg/1819t2is415/Signal_Proposal) and the [Shiny application](https://is415-ay1819-signal.shinyapps.io/Signal/).

-   AY2020-2021 Term 1

    -   [J-Town](https://is415-t14-project-proposal.netlify.app/) and the [Shiny Application](https://erika-aldisa-gunawan.shinyapps.io/IS415_T14_EastKalimantan_New_JTown/)

-   AY2021-2022 Term 1

    -   Group 1: [Spatial Interaction Model](https://flosg-is415.netlify.app/)
    -   Group 3: [Regionalisation in Reach](https://is412-g3-proposal.netlify.app/posts/welcome/)
    -   Group 5: [Geographically Weighted Regression](https://g5-is415-proj.netlify.app/)
    -   Group 7: [GeoeXplorer](https://geoxplorer.netlify.app/), a web-enabled geospatial analytics toolkit for detecting and visualising global spatial autocorrelation and local clusters and outliers from univariate geographically referenced data.
    -   Group 8: [Spatial Pointers](https://spatial-pointers.netlify.app/project-proposal), a web-enabled Spatial Point Patterns Analysis toolkit for visualising and analysing both spatial and network constrained point patterns.

-   AY2022-2023 Term 1

-   Group 1: [This is FINE: Fire INcidents Explorer](https://is415-fire-incidents-explorer.netlify.app/)

-   Group 2: [Spatial Bros](https://spatialbros.netlify.app/)

-   Group 3: [Analysis of Resale HDB Prices](https://is415-geospatial-project-g1t3.netlify.app/)

-   Group 4: [GeoNinjas](https://is415-gaa-valencia-derek-yashica.netlify.app/)

-   Group 5: [Transit-Ability](https://is415-group-5.netlify.app/)

-   Group 6: [CrimeIndia](https://is415gg-gally.netlify.app/)

-   Group 7: [The Right Space](https://is415-g1t7-project.netlify.app/)

-   Group 8: [CarSpot: Geospatial Parking Analysis!!](https://is415-group8.netlify.app/)

-   Group 9: [Dr Go Where](https://is415-group9.netlify.app/)

-   Group 10: [Spatial Point Pattern Analysis on Seoul's healthcare accessibility](https://is415-project-g10.netlify.app/project_outline)

-   Group 11: [Regress Rangers](https://is415-team15-proj.netlify.app/)

-   Group 12: [Spatial Point Pattern Analysis of Airbnb listings in Beijing](https://is415-grp12.netlify.app/)

## Project Links

-   [Group 2: CrimeWatch - Vietnam Law and Order](https://is415-g2-crimewatch.netlify.app/)
-   [Group 3: SimplyGEO-Analysing Push-Pull Factors for Public Bus Demand in Singapore Using Spatial Econometric Interaction Modelling](https://is415-gaa-project-group3.netlify.app/). The project website is well designed, providing a clear and comprehensive description of the project, UI design, and User Guide.  The project minutes were well documented.
-   [Group 4: ELDANALYZE: Simple Geospatial Analysis Using Shiny](https://project-gaa-t4.netlify.app/)
-   [Group 5: Culinary Crossroads](https://culinarycrossroads.netlify.app/)
-   [Group 6: RecycleSG](https://is415-gaa-jkw.netlify.app/)
-   [Group 7: WhatTown](https://is415-gaa-g1t7-23-24.netlify.app/). The Shiny application is very well designed.  Able to provide a collection of useful UIs for calibrating the Accessibility models and Spatial Point Patterns Analysis. 
-   [Group 8: Quake Quest!](https://is415-gaa-g1g8.netlify.app/)
-   [Group 9: Happy Hideouts](https://happy-hideouts.netlify.app/)
-   [Gourp 10: ThaiRoad - Spatial Points Pattern Analysis on Road Accidents in Thailand](https://gga-thairoad.netlify.app/)
-   [Group 11: HealthGeo Cambodia](https://is415-healthgeo-cambodia.netlify.app/)
-   [Group 12: Enhancing Urban Living](https://is415-gaa-russelltjh.netlify.app/project/project_proposal)
-   [Group 13: Project Daylight](https://is415-project-daylight.netlify.app/)
-   [Group 14: GeoMommy](https://geomommy.netlify.app/)
