---
title: "Syllabus"
editor: visual
---

## Synopsis

Where should the next new business outlet be located in order to optimise the profit? What are the location factors that affect the resale prices of HDB housing units? Which are the economic or service activities such as IT professional firms, car workshops, fast food chains (ie. KFC, McDonalds), coffee outlets (Starbucks, Ya Kun Kaya Toast, Toast Box) that tend to be located close to one another and which are the ones that tend to be a distance apart? Do these observed patterns and processes occur at random or are they being constrained by geographical factors? These and many other related questions are the challenges faced by data scientists and data analysts today especially when geographical data are used.

Geospatial analytics offers the solutions to these questions by providing data scientists and analysts a problem-driven and data-centric analysis framework focusing on discovering actionable understanding from geographically referenced data. It makes extensive use of geospatial data wrangling, geoprocessing, spatial statistical, geospatial machine learning and spatial data visualisation techniques to support decision- and strategy-making.

This course provides students with an introduction to the concepts, principles and methods of geospatial analytics and their practical applications of geospatial analytics in real world operations. Emphasis will be placed on

-   performing geospatial data science tasks such as importing, tidying, manipulating, transforming, projecting and processing geospatial data programmatically,
-   visualising, analysing and describing geographical patterns and process using appropriate geovisualisation and thematic mapping techniques,
-   Conducting geospatial analysis by using appropriate spatial statistics and machine learning methods and
-   building web-based geospatial analytics applications.

## Course Objectives

Upon completion of the course, students will be able to:

-   Provide accurate explanation of the mathematical and input data requirements of the analysis method(s) used,
-   Import, extract, process, transform and assemble geospatial analytical sandbox programmatically to meet the analysis needs,
-   Apply appropriate geospatial analysis methods in addressing specific analysis tasks,
-   Communicate the analysis procedures in a reproducible manner,
-   Communicate the analysis results effectively and in an easy to understand manner with the help of appropriate geo- and data visualisation techniques, and
-   Design and implement web-enabled geospatial analytics applications.

## Competencies

1.  Defining Geospatial Analytics and describing the applications of geospatial analytics by using real-world examples.
2.  Explaining the differences between Geospatial Analytics and Geographic Information Systems (GIS).
3.  Importing, wrangling and transforming aspatial data by using tidyverse family of packages
4.  Importing, wrangling and transforming geographical data by sing sf package.
5.  Geocoding and georeferencing geographical data programmatically.
6.  Performing geoprocessing operations programmatically by using sf packages.
7.  Performing Exploratory Data Analysis (EDA) using ggplot2 and Confirmatory Data Analysis using ggstatsplot.
8.  Preparing cartographic quality analytical maps by using tmap package.
9.  Visualising and analysing multivariate geospatial data using corrplot and heatmaply packages.
10. Explaining the principles and methods of spatial point patterns and complete spatial randomness.
11. Performing spatial point pattern analysis by using appropriate R package(s) and providing accurate interpretation of the analysis results.
12. Explaining the principles and methods of spatial weights.
13. Computing spatial weights by using appropriate functions of spdep package.
14. Explaining the concepts of spatial autocorrelation, spatial clusters, hot spot and cold spot areas.
15. Computing localised geospatial statistics by using appropriate R package(s) and providing accurate interpretation of the analysis results.
16. Explaining the principles of explanatory modelling and methods of geographically weighted regression.
17. Calibrating geographically weighted regression models by using appropriate R package(s) and providing accurate interpretation of the analysis results.
18. Explaining the concept of geographic segmentation and methods of spatially constrained clustering.
19. Performing spatially constrained cluster analysis by using appropriate R package(s) and providing accurate interpretation of the analysis results.
20. Explaining the concept of spatial dependency and methods of spatial interpolation.
21. Performing spatial interpolation by using appropriate R package(s) and providing accurate interpretation of the analysis results.
22. Defining geographic accessibility and explaining the methods of accessibility analysis.
23. Performing geographic accessibility analysis by using appropriate R package(s) and providing accurate interpretation of the analysis results.
24. Designing geospatial application programmatically by using free and open source software and packages (i.e. R, R packages and Shiny).

## Prerequisites/Co-requisites

NIL. (But a basic working knowledge of computer and numeracy will be assumed. Students are expected to understand Windows-based operating systems and to manage files and disk space responsibly. **More importantly, students taking this course must be willing to learn R programming**.)

## Course Assessments

| Assessment Categories        | Weighting (%) |
|------------------------------|---------------|
| Hands-on Exercise (2% x 10)  | 20%           |
| In-class Exercise (2% x 10)  | 20%           |
| Take-home Exercise (10% x 3) | 30%           |
| Geospatial Analytics Project | 30%           |


## Course Assessment Details

### Pre-lesson Learning and Class Participation

Pre-lesson learning materials, namely: videos, slides, recommended readings and hands-on exercises will be released one week before the weekly lesson starts. A strict requirement for each class meeting is to complete the assigned pre-learning materials before coming to class. Students are required write down at least one question or issue encountered while viewing the video, reading the recommended articles or working on the hands-on exercises and post them on Piazza for discussion.

Student sharing of insights from readings of assigned materials on Piazza will form a large part of the learning in this course.


### Hands-on Exercise (20%)

Hands-on exercises aim to provide students to gain hands-on experience on using selected R packages to perform geospatial analysis with real world use cases. It is important for students to complete the hands-on exercises before class.

### In-class Exercise (20%)

In-class exercise and discussion will extend the methods learned from the hands-on exercise to advanced modelling. The in-class discussion will also focus on how to interpret the analysis results and to communicate the analysis results by using appropriate map and data visualisation techniques. Students may also be quizzed in class and thereby contribute to in-class exercise.

### Take-home Exercise (30%)

There are three take-home exercises that are due throughout the term. They aim to provide students the opportunities to apply the methods learned in class by working through mini real-world cases. Each take-home exercise is an extension of the hands-on and in-class exercises. What this means is that, for example, in Lesson 1, students will learn the concept of spatial point processes and the hands-on exercise will provide students step-by-step guide on how to use R packages to perform spatial point patterns analysis. The in-class discussion, beside clarification of the concepts and usage of R packages syntax and argument, it will focus more on how to interpret and communicate the analysis results. Then the take-home exercise will require students to synthesise what they have learned from the readings, hands-on exercise and in-class exercise. The estimated workload will be about 6-8 hours per week.

Each take-home exercise will carry a same weightage of 10%. The deliverable format of the take-home exercises and marking rubric of will be provided on the handout of the take-home exercise. Feedback on take-home exercise will be provided weekly before the weekly lesson starts. This is to ensure that students will learn from mistakes made in the earlier take-home exercise and improve their work progressively in the subsequent take-home exercises.

Students may work together to help one another with computer or geospatial issues and discuss the materials that constitute the take-home exercise. However, each student is required to prepare and submit the take-home exercise (including any computer work) on their own. Cheating is strictly prohibited. Cheating includes but not limited to: plagiarism and submission of work that is not the student’s.

### Geospatial Analytics Project (30%)

The purpose of the geospatial analytics project is to provide students first hand experience on building web-based geospatial analytics tool by integrating open source web mapping API(s), data visualisation API(s) and geospatial analysis libraries. You will also learn how to collecting, processing and analysing spatially related issues using real world data. Students are encouraged to focus on research topics that are relevant to their field of study.

### Final Exam

There will be no final examination for this course.
