---
title: "Lesson 8: Hierarchical Clustering for Multivariate Geographically Referenced Data"
date: "July 25, 2024"
date-modified: "last-modified"
format: html
toc: true
---

## Overview

## Content

-   Basic concepts of clustering analysis
-   Hierarchical clustering methods
    -   Proximity matrices
    -   Agglomerative hierarchical clustering algorithms
-   Hierarchical clustering processes and best practices

## Lesson slides

-   [Lesson 8: Hierarchical Clustering for Multivariate Geographically Referenced Data](..\lesson\Lesson08\Lesson08.pdf) slides.

## Hands-on Exercise

-   [12 Geographical Segmentation with Spatially Constrained Clustering Techniques](https://r4gdsa.netlify.app/chap12.html), **Section 12.1-12.7** only.

## References

-   Rovan, J. and Sambt, J. (2003) ["Socio-economic Differences Among Slovenian Municipalities: A Cluster Analysis Approach"](http://mrvar.fdv.uni-lj.si/pub/mz/mz19/rovan.pdf), *Developments in Applied Statistics*, pp. 265-278.\
-   Demeter, T. and Bratucu, G. (2013) ["Statistical Analysis Of The EU Countries from A Touristic Point of View"](https://webbut.unitbv.ro/index.php/Series_V/article/view/5438), *Bulletin of the Transilvania University of Braşov*, 6(55): 121-130.
-   Brown, N.S. & Watson, P. (2012) ["What can a comprehensive plan really tell us about a region?: A cluster analysis of county comprehensive plans in Idaho"](https://ageconsearch.umn.edu/record/176591/files/WEFFall2012v11n2_Brown.pdf), Western Economics Forum. Pp.22-37.

### All About R

-   [Hierarchical Cluster Analysis](http://uc-r.github.io/hc_clustering).
