---
title: "Lesson 10: Regression Modelling of Geographically Reference Data"
date: "July 25, 2024"  
date-modified: "last-modified"
format: html
editor: visual
---

In this lesson, you will learn the basic concepts and methods of simple and multiple linear regression and their applications on geographically referenced data.

## Content

-   Basic concepts and principles of linear regression
    -   Simple linear regression 
    -   Multiple linear regression
-   Regression Diagnostics
    -   Linearity: The relationship between X and the mean of Y is linear.
    -   Homoscedasticity: The variance of residual is the same for any value of X.
    -   Independence: Observations are independent of each other.
    -   Normality: For any fixed value of X, Y is normally distributed.
-   The spatial stationarity assumption of multivariate regression.

## Lesson Slides and Hands-on Notes

-   [Lesson 10 slides](../lesson/lesson10/lesson10.pdf).

-   [Hands-on Exercise 8](https://r4gdsa.netlify.app/chap13.html).  **Section 13.1-13.8** only.

## References


## All About R


